spring.profiles.active=prod

server.port=8082

spring.jpa.properties.hibernate.jdbc.batch_size=30
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
logging.level.ru.hogwarts.school=INFO